### ISSUE TITLE
Error prompt on rEFInd interface

### ISSUE THREAD

**Issue by YijieDeng** [0xbb/apple_set_os.efi#21]
Hi, I saw a error message when starting the efi through rEFInd, ~the error message says "a1060012" error code~ It says "could not set version" and returns a error code different each time I boot up my macbook. What does this mean? Thank you!

**Comment by ah-** [comment]
Hi, did this start after updating to Catalina? Maybe have a look here: https://github.com/0xbb/apple_set_os.efi/issues/20

**Comment by YijieDeng** [comment]
I see, it is the same issue, not quite sure how will it be fixed if ever in future though. Thank you!
