### ISSUE TITLE
Use the same EFI trick to fix the NVMe driver in 2013/2014 Macbook?

### ISSUE THREAD

**Issue by 360fun** [0xbb/apple_set_os.efi#22]
Hi, I landed on this github project because I was looking for an easier way to patch the **EFI Boot ROM** in order to fix the **DXE NVMe Driver** of 2013/2014 Macbooks.

[In this thread is very well explained the problem/situation of NVMe SSD.](https://forums.macrumors.com/threads/upgrading-2013-2014-macbook-pro-ssd-to-m-2-nvme.2034976/)

The user **Cmd+Q** [made a guide](https://forums.macrumors.com/threads/upgrading-2013-2014-macbook-pro-ssd-to-m-2-nvme.2034976/page-65#post-26224320) to do it with an **CH341A programmer** (very cheap) + **SPI to J6100 cable** (expensive).

This procedure is [pretty complicated, risky, expensive](https://kaspa.rs/upgrading-macbook-pro-2013-2014-nvme-drive/) and you need to repeat it if MacOS upgrades the BootRom (might not happen anymore...but who knowns).

**I was wondering if (since MacOS is able to upgrade the driver) is possible to achieve the same via a software hack.**

**Comment by satmandu** [comment]
Apologies for necrobumping, but this issue is resolved by the EFI nvme driver which is installed by the macos Big Sur installer, at least for devices supported by Big Sur, like the mid-2014 MacBookPro (MacBookPro11,3).

**Comment by 360fun** [comment]
Yes! I also forgot about this issue eheh 😅 time to close it ;)
