### ISSUE TITLE
Does not work on Macbook Pro 11,3 and Ubuntu 21.04

### ISSUE THREAD

**Issue by aliris-schmidt** [0xbb/apple_set_os.efi#24]
I try to get this to work on my Macbook Pro 11,3 with single OS Ubuntu 21.04 but it just wont work. lspci |grep VGA only displays the discrete graphics. I followed the instructions step by step. Does anyone have an idea how to go on?
Just switched to Ubuntu as the Macbook Pro 11,3 wont be supported in the coming MacOS. Linux seems great but I really would love to use the integrated graphics.

Thank you all!

**Comment by aliris-schmidt** [comment]
I tried the solution with changing the APPLE_SET_OS_VERSION to 10.15 but this also wouldnt show the integrated graphics in linux. 
Does this not work because I use Ubuntu as single system? I had MacOS BigSur installed before but now just Ubuntu as single system.

**Comment by aliris-schmidt** [comment]
I just read my problem could be due to my apple firmware version? did anyone have the same problem?

**Comment by aliris-schmidt** [comment]
Also tried to set it to "macOS 11.0" and compile it. Still the internal GPU is not recognized.

**Comment by aliris-schmidt** [comment]
Dont know what difference in the order of commands, or the difference in the 40_custom grub file made, but this solution worked.
I also did the sudo grub-update in my tries before.

https://gist.github.com/stefanocoding/c6dbf4489f330021bd9335d655c9fbbf

**Comment by palmerj** [comment]
Heya @aliris-schmidt how did you get this working? Did you end up recompiling with APPLE_SET_OS_VERSION set to a higher version? I'm running MacBookPro11,3 on 20.04.3 and Kernel 5.8, but I'm considering upgrading to kernel version 5.11 to see if that help.

I can't get gdm to start. See https://gist.github.com/stefanocoding/c6dbf4489f330021bd9335d655c9fbbf#gistcomment-3870400

**Comment by aliris-schmidt** [comment]
Hi @palmerj I used the exact same howto I linked above just yesterday on a clean new install of 21.10 on a MacBookPro 11,3. Only difference, I had to sudo the ./gpu-switch -i
I used the standard v1 apple_set_os.efi here.

**Comment by palmerj** [comment]
Thank you very much for the reply. I might have to install 21.10. What version kernel are you running?

As a side note I've also have issue with the laptop not resuming after closing the lid. The computer suspends ok, but then I open the lid it locks up and I get a black screen. What version of the NVIDIA drivers do you have installed? I've got 460.91.03 installed from nividia-driver-460 package. I upgraded to these drivers so I can set the display to 150% fractional scaling.

**Comment by palmerj** [comment]
Also can you please confirm the version of firmware that you have installed? I have EFI Version 429.0.

```
sudo dmidecode | grep "EFI Version"
Wrong DMI structures length: 2667 bytes announced, only 2449 bytes available.
	String 1: Apple ROM Version.  Model:        MBP112.  EFI Version:  429.0.
Invalid entry length (0). DMI table is broken! Stop.
```

Thank you

**Comment by aliris-schmidt** [comment]
5.11.0-31-generic

390.144

Model:        MBP112.  EFI Version:  431.0.

**Comment by palmerj** [comment]
Thank you. I can see if these versions help, however I would rather keep the version 460 version of the Nvidia driver. Did you try to get fractional scaling going with the 390 drivers?

What opening the lid from suspending the laptop? Is that ok for you?

Cheers and many thanks again

**Comment by aliris-schmidt** [comment]
Hi, I tried fractional scaling but the display did not look as sharp as on 100% or 200%. Opening the lid wakes up my laptop just fine.
As I'm using "Dash to Panel" I just changed the Icon size of the dock o my needs and the system font in tweaks so I do not need to use fractional scaling. Rest is done with "App Grid Tweaks" Gnome Extension.

**Comment by palmerj** [comment]
> Hi, I tried fractional scaling but the display did not look as sharp as on 100% or 200%.

Thanks once again! Sorry to continue to be a pain but can you share your exact setting before I decide to reinstall? Are you using 100% or 200% scaling? I tried many tweaks (i.e system fonts sizes + font scaling factor) when setting at 100%, but I found the windows title buttons were too small, and the fonts in the menu bar with certain. 

When I use 150% factional scaling and the following font tweaks I get a really nice result:

![gnome-shell-screenshot-KA6N80](https://user-images.githubusercontent.com/580022/130866162-ae054e0c-1894-48a2-b773-f3a823307e9d.png)

![gnome-shell-screenshot-N6RP80](https://user-images.githubusercontent.com/580022/130866204-06854d66-59f2-4855-b7b9-a98f55baf6bb.png)

> Opening the lid wakes up my laptop just fine.

Great. I also experienced this with the 390 drivers after a fresh install. If I can solve the scaling issue I can go back to these.

> As I'm using "Dash to Panel" I just changed the Icon size of the dock o my needs and the system font in tweaks so I do not need to use fractional scaling. Rest is done with "App Grid Tweaks" Gnome Extension.

Ok sounds like an interesting setup, and maybe this help with the window title and menu bar issues I saw when using 100% scaling?

Thanks again for sharing.

**Comment by aliris-schmidt** [comment]
right now I’m using 200% scaling. I scaled down the most annoying parts, like the overly large icons with said method. I found some ideas of another dude here. https://gist.github.com/johnjeffers/3006011ec7767a4101cdd118e8d64290

**Comment by palmerj** [comment]
Thanks @aliris-schmidt :-) I got some time this weekend to do a fresh install of 21.04 and it works well, and I can now use the intel GPU! When using the Intel GPU I can even use 150% scaling which is nice. Do you mostly just use the intel GPU, or are your switching? Have you tried the on-demand setting, or just have it set to the power saving mode in the prime profiles?

**Comment by yue-dongchen** [comment]
@aliris-schmidt @palmerj I encounter a completely blank screen after "welcome to GRUB". Removing apple_set_os.efi lets the GRUB menu appear normally, so it's definitely found. Did you not update to 11.x?
MBP112.  EFI Version:  429.0.

**Comment by tomodachi** [comment]
I've noticed fractional scaling looks great on Wayland (but ofc can't use the nvidia driver then)

In Sway with fractional scaling of 1.53x everything looks crisp and a perfect size for the screen.

Is it possible to use Nvidia prime on the Macbook in Linux? assumed it only worked on ordinary PC Laptops.

I mostly use intel ,but use gpu_switch and reboot when I want to use external monitor
