### ISSUE TITLE
apple_set_os.efi stop worked

### ISSUE THREAD

**Issue by crrlcx** [0xbb/apple_set_os.efi#4]
MacBookPro11,5
macOS Sierra 10.12.4
UEFI ver: MBP114.88Z.0172.**B16**.1702161608 date: 02/16/2017

#### Debian Stretch [Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux]
- gnu-efi 3.0.4-2
- grub-efi 2.02~beta3-5
- libefiboot1 30-1
- libefivar1 30-1

**Comment by crrlcx** [comment]
> Starting from macOS 10.12.4 (or if you have done macOS 10.12.3 reinstallation), Apple’s MBP firmwares are not compatible with 0xbb’s apple_set_os.efi due to a different version number.
[discussion is here](https://egpu.io/forums/mac-setup/how-to-keep-mbps-irisiris-pro-activated-when-booting-into-windows-boot-camp/)

**Comment by soundg33k** [comment]
Same here:
MacBookPro11,5
macOS Sierra 10.12.4

Stop working since I installed 10.12.4 

It would be nice to bring the changes to GitHub... if the they are working. I don't know what is the fix exactly from the author of the thread on the link you sent.

**Comment by 0xbb** [comment]
@soundg33k Thanks for testing. I pushed a bugfix + published a new binary.
