### ISSUE TITLE
Doesn't boot on 2015" MBP with dGPU

### ISSUE THREAD

**Issue by shamilovtim** [0xbb/apple_set_os.efi#5]
1. File is on USB thumb drive
2. Hold option key at boot, select thumb drive
3. Instant error screen with message: "Your computer has been restarted because of a problem"
4. Allowing it to restart simply puts me back in MacOS

**Comment by shamilovtim** [comment]
Have attempted booting with the file on refind and nothing plugged into MacBook. Still doesn't boot.  2015 MBP with Radeon M370x Sierra 10.12.5.

**Comment by shamilovtim** [comment]
Last logged message received before stalled bootup on refind is here.

![img_2578](https://user-images.githubusercontent.com/3495974/27440844-e603a542-5739-11e7-865c-e54deed80d6b.JPG)

**Comment by csantiago78** [comment]
Experiencing the same issue here on V1

**Comment by shamilovtim** [comment]
I got it to work with some fiddling once I had the file on refind

**Comment by almssp** [comment]
@shamilovtim care to post how you did ?

**Comment by shamilovtim** [comment]
I installed refind and the boot was accessible that way. USB stick doesn’t work

**Comment by shamilovtim** [comment]
Closing this. To resolve, install the file into a bootloader (e.g. refind) rather than trying to access it through USB.
